"use strict";
exports.__esModule = true;
var Biblioteca_1 = require("./Biblioteca");
var Libro_1 = require("./Libro");
var Socio_1 = require("./Socio");
var Libro1 = new Libro_1.Libro('El Principito', 'Antoine de Saint-Exupéry', 'Narrativo', true);
var Libro2 = new Libro_1.Libro('Los Viajes de Gulliver', 'Jonathan Swift', 'Fantastico', true);
var Libro3 = new Libro_1.Libro('El Viejo y el Mar', 'Ernest Hemingway', 'Novela', true);
var Libro4 = new Libro_1.Libro('El Principe', 'Nicolás Maquiavelo', 'Historico', true);
var Libro5 = new Libro_1.Libro('El Origen de las Especices', 'Charles Darwin', 'Ciencia', true);
var ListadoLibros = [];
var Socio1 = new Socio_1.Socio('Gustavo', 'González', 30597845, ListadoLibros);
var Socio2 = new Socio_1.Socio('Gabriel', 'Lopez', 35485965, ListadoLibros);
var Socio3 = new Socio_1.Socio('Belen', 'Fernandez', 39554846, ListadoLibros);
var ListadoSocios = [];
var BibliotecaNueva = new Biblioteca_1.Biblioteca(ListadoLibros, ListadoSocios, 'Biblioteca "Manuel Belgrano".');
BibliotecaNueva.anotarLibro(Libro1);
BibliotecaNueva.anotarLibro(Libro2);
BibliotecaNueva.anotarLibro(Libro3);
BibliotecaNueva.anotarLibro(Libro4);
BibliotecaNueva.anotarLibro(Libro5);
BibliotecaNueva.anotarSocio(Socio1);
BibliotecaNueva.anotarSocio(Socio2);
BibliotecaNueva.anotarSocio(Socio3);
BibliotecaNueva.retirarLibro(Libro1);
BibliotecaNueva.consultarLibro(Libro1);
